databases:
- name: postgres
  ipAllowList: []

services:
- type: web
name: piazza-web
env: ruby
plan: free
numInstances: 1
buildCommand: ./bin/render-build.sh
startCommand: bundle exec rails
envVars:
- key: RAILS_MASTER_KEY
  sync: false
- key: DATABASE_URL
  fromDatabase:
    name: piazza-db
    property: connectionString
